Stats API
dcsaorg/DCSA-OpenAPI pull request #170
Opened 2023-09-27 13:40 UTC by douradofrazer

2024-01-04 13:57 UTC, HenrikHL commented
I don't know if this API is still relevant - I have approved a PR with a correct definition for the Stats API here: https://github.com/dcsaorg/DCSA-Stats-API/blob/master/stats-api-specs.yaml

2024-01-18 12:02 UTC, HenrikHL requested changes
Please copy from Stats repositroy master
Please add new endPoint in separate PR

2024-01-18 13:19 UTC, douradofrazer commented
> Please copy from Stats repositroy master Please add new endPoint in separate PR

Not gonna recopy it, only the type was a problem. I rechecked your commits on the master repo and realized I missed one commit.
I am checking the error object so updating that.

2024-01-18 14:22 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +      description: This endpoint allows you to report the daily usage statistics of a all DCSA APIs being used.
There is something wrong with the wording in the end of this description. Maybe the `a` should be removed between `of` and `all`...

2024-01-18 14:26 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +            - `BKG` (Booking Notifications)
```suggestion
            - `BKG_NTF` (Booking Notifications)
```

2024-01-19 10:46 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +                    requestUri: /v1/stats
customized example here is wrong - should be /v1/stats-summary

2024-01-19 10:47 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +                    requestUri: /v1/stats
same

2024-01-19 10:47 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +                    requestUri: /v1/stats
same

2024-01-19 10:57 UTC, HenrikHL commented on stats/v1/STATS_v1.0.0-Beta-1.yaml
> +          description: Statistics created date in `ISO 8601` format.
Is it on purpose that you have this field inside the payload stats-summary array?

2024-04-25 08:11 UTC, HenrikHL commented
Stats API is being discontinued here

2024-04-25 08:11 UTC, closed without merging