APCV-1037 and APCV-927 changes
dcsaorg/DCSA-OpenAPI pull request #250
Opened 2024-05-07 12:19 UTC by palatsangeetha

Added cursor to vesselSchedules
Added location discriminator
Added additionalProperties:false to UNLocationLocation

2024-05-07 12:38 UTC, HenrikHL requested changes
You have to change the version number of the API as well (line 6 of the API)

2024-05-08 10:55 UTC, HenrikHL submitted a review, later dismissed
I agree with the changes. Now it needs to be agreed if this is a Bug-fix release
If it is a bug-fix - should the issues in the ErrorObject be fixed as well?

2024-05-08 11:26 UTC, emiliodcsa commented on ovs/v3/OVS_v3.0.1.yaml
> +          discriminator:
Hi @palatsangeetha , why is this a change if already present in 3.0.0? 
<img width="776" alt="image" src="https://github.com/dcsaorg/DCSA-OpenAPI/assets/109235796/44fb13fb-a6a0-4cd1-ac17-8cddd2ed6af9">

2024-05-16 08:12 UTC, HenrikHL commented on ovs/v3/OVS_v3.0.1.yaml
> +            type: string
please add the limitation we agreed on in the chat

2024-05-16 08:18 UTC, HenrikHL submitted a review, later dismissed

2024-05-16 11:52 UTC, HenrikHL approved these changes

2024-05-16 11:54 UTC, merged